# SPRING
spring:
  # SERVLET
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  # JPA
  jpa:

    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      format_sql: true

  # DATASOURCE
  datasource:
    url: jdbc:postgresql://localhost:5433/kbi_test_db
    username: user
    password: user


# LOGGING
logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

server:
  port: ${PORT_SERVER:8085}
